/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { MemberSummary } from './memberSummary';
import type { AdminRentalHistoryDetailRentalStatus } from './adminRentalHistoryDetailRentalStatus';

export interface AdminRentalHistoryDetail {
  rentalHistoryId: number;
  member: MemberSummary;
  itemName: string;
  rentAt: string;
  returnedAt?: string;
  rentalStatus: AdminRentalHistoryDetailRentalStatus;
  itemCode?: string;
}
