/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { AdminRentalHistoryDetail } from './adminRentalHistoryDetail';

export interface AdminRentalHistoryFindAllResponse {
  rentalHistories: AdminRentalHistoryDetail[];
  /** 총 페이지 수 */
  totalPage: number;
}
