/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */

/**
 * 관리자 역할
 */
export type AdminMemberDetailRole = typeof AdminMemberDetailRole[keyof typeof AdminMemberDetailRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminMemberDetailRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  WORKER: 'WORKER',
  GA: 'GA',
} as const;
