/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { RentalTime } from './rentalTime';

/**
 * 관리자 전용 대여기록 추가 DTO
 */
export interface AdminRentalHistoryRequest {
  /** 대여자 ID */
  memberId: number;
  /** 대여할 물품의 ID */
  itemId: number;
  /** 대여할 물품의 수량 */
  count: number;
  /** 대여 시작 시간 정보 */
  rentalTime: RentalTime;
  /** 근무자 ID */
  workerId: number;
}
