/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { PosterDetail } from './posterDetail';
import type { DisplayResponseSchedulesItem } from './displayResponseSchedulesItem';
import type { DisplayItemDetail } from './displayItemDetail';

export interface DisplayResponse {
  posters: PosterDetail[];
  schedules: DisplayResponseSchedulesItem[];
  items: DisplayItemDetail[];
}
