/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */

export type GetSchedulesParams = {
/**
 * 조회 시작일
 */
startDate: string;
/**
 * 조회 종료일
 */
endDate: string;
};
