/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */

export interface ItemSummary {
  /** 물품 이름 */
  itemName: string;
  /** 물품 아이콘 URL */
  imageUrl: string;
}
