/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { ItemDetailItemType } from './itemDetailItemType';

export interface ItemDetail {
  /** 물품 ID */
  itemId: number;
  /** 물품 이름 */
  itemName: string;
  /** 물품 타입 */
  itemType: ItemDetailItemType;
  /** 물품 개수 */
  count: number;
  /** 물품 아이콘 URL */
  imageUrl: string;
}
