/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */

export type NotificationDetailStatus = typeof NotificationDetailStatus[keyof typeof NotificationDetailStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationDetailStatus = {
  ADMIN_RENTAL_APPLY: 'ADMIN_RENTAL_APPLY',
  ADMIN_RENTAL_CANCEL: 'ADMIN_RENTAL_CANCEL',
  ADMIN_RETURN_APPLY: 'ADMIN_RETURN_APPLY',
  ADMIN_RETURN_CANCEL: 'ADMIN_RETURN_CANCEL',
  USER_RENTAL_APPLY: 'USER_RENTAL_APPLY',
  USER_RENTAL_APPROVED: 'USER_RENTAL_APPROVED',
  USER_RENTAL_REJECTED: 'USER_RENTAL_REJECTED',
  USER_RETURN_APPLY: 'USER_RETURN_APPLY',
  USER_RETURN_APPROVED: 'USER_RETURN_APPROVED',
  USER_RETURN_COMPLETED: 'USER_RETURN_COMPLETED',
} as const;
