/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */

export interface PayerSummary {
  /** 납부자 ID */
  payerId: number;
  /** 납부자 이름 */
  name: string;
  /** 납부자 학번 */
  studentId: string;
  /** 서비스 가입 여부 */
  registered: boolean;
}
