/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { RentalStatusWorkerLogDetailRentalStatus } from './rentalStatusWorkerLogDetailRentalStatus';
import type { MemberSummary } from './memberSummary';

export interface RentalStatusWorkerLogDetail {
  /** 대여 상태 */
  rentalStatus: RentalStatusWorkerLogDetailRentalStatus;
  /** 처리자 정보 */
  worker?: MemberSummary;
  /** 상태 변경 시각 */
  createdAt: string;
}
