/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { MemberSummary } from './memberSummary';
import type { ItemSummary } from './itemSummary';
import type { RentalHistoryDetailRentalStatus } from './rentalHistoryDetailRentalStatus';

/**
 * 대여 이력 상세 정보
 */
export interface RentalHistoryDetail {
  /** 대여 이력 ID */
  rentalHistoryId: number;
  /** 대여한 회원의 요약 정보 */
  member: MemberSummary;
  /** 대여한 물품의 요약 정보 */
  item: ItemSummary;
  /** 대여 시작 시각 */
  rentAt: string;
  /** 반납 시각 (반납되지 않았으면 null) */
  returnedAt?: string;
  /** 대여 상태 */
  rentalStatus: RentalHistoryDetailRentalStatus;
}
