/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */

/**
 * 대여 시작 시간 (시간 및 분)
 */
export interface RentalTime {
  /** 대여 시작 시각의 시간(24시간 기준) */
  hour: number;
  /** 대여 시작 시각의 분 */
  minute: number;
}
