/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { RentalTime } from './rentalTime';

/**
 * 대여 기록 생성 요청 DTO
 */
export interface RentalHistoryRequest {
  /** 대여할 물품의 ID */
  itemId: number;
  /** 대여할 물품의 수량 */
  count: number;
  /** 대여 시작 시간 정보 */
  rentalTime: RentalTime;
  /** 중복 대여 무시 여부 (true인 경우 중복 대여 진행) */
  ignoreDuplicate: boolean;
}
