/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { ReturnRequiredItemDetail } from './returnRequiredItemDetail';

/**
 * 반납이 필요한 물품들의 목록 응답
 */
export interface ReturnRequiredItemFindAllResponse {
  /** 반납이 필요한 물품 상세 정보 목록 */
  items: ReturnRequiredItemDetail[];
}
