/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * 빌릴게(Billilge) API
 * 국민대학교 소프트웨어융합대학 복지물품 대여 서비스
 * OpenAPI spec version: v1
 */
import type { ItemSummary } from './itemSummary';

/**
 * 반납이 필요한 물품 상세 정보
 */
export interface ReturnRequiredItemDetail {
  /** 물품 요약 정보 */
  item: ItemSummary;
  /** 대여 일수 (예: D+1에서의 1) */
  rentalDayCount: number;
}
